# app/.helm/values.yaml

replicaCount: 2

image:
  repository: "cr.yandex/crptc1fo9pblspme31kb/my-spring-app"
  tag: "v1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "500m"
    memory: "512Mi"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: java-app.example.com
      paths:
        - path: /
          pathType: Prefix
